using AutoMapper;
using CarsDealersManagement.Application.Interfaces;
using CarsDealersManagement.Domain.Base;
using CarsDealersManagement.Domain.Entities;
using CarsDealersManagement.Domain.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace CarsDealersManagement.Application.Services
{
    public class ApplicationUserService(IMapper mapper, 
        IConfiguration configuration, 
        IEmailSender emailSender, 
        UserManager<ApplicationUser> userManager, 
        SignInManager<ApplicationUser> signInManager) : IApplicationUserService
    {
        private readonly IMapper _mapper = mapper;
        private readonly IConfiguration _configuration = configuration;
        private readonly IEmailSender _emailSender = emailSender;
        private readonly UserManager<ApplicationUser> _userManager = userManager;
        private readonly SignInManager<ApplicationUser> _signInManager = signInManager;

        public async Task<TokenDto> GetAccessTokenAsync(LoginRequestDto message)
        {
            var user = await _userManager.FindByNameAsync(message.UserName);

            if (user == null)
            {
                throw new Exception("Given user name does not exist in the system");
            }

            if (!await _userManager.CheckPasswordAsync(user, message.Password))
            {
                await _userManager.AccessFailedAsync(user);
                throw new Exception("Username or password and not valid.");
            }

            var userRoles = await _userManager.GetRolesAsync(user);

            var authClaims = new List<Claim>
            {
                new(ClaimTypes.Name, user.UserName!),
                new(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
            };

            foreach (var userRole in userRoles)
            {
                authClaims.Add(new Claim(ClaimTypes.Role, userRole));
            }

            var token = GetToken(authClaims);

            return new TokenDto
            {
                AccessToken = new JwtSecurityTokenHandler().WriteToken(token),
                ExpiresIn = new DateTimeOffset(token.ValidTo).ToUnixTimeMilliseconds()
            };
        }

        public async Task<LoginResponseDto> LoginUserAsync(LoginRequestDto message)
        {
            var user = await _userManager.FindByNameAsync(message.UserName);

            if (user == null)
            {
                throw new Exception("Given user name does not exist in the system");
            }

            if (await _userManager.IsLockedOutAsync(user))
            {
                throw new Exception("Your account is locked due to multiple failed login attempts. Please contact the system administrator.");
            }

            if (!await _signInManager.CanSignInAsync(user))
            {
                throw new Exception("A confirmation email had been sent to you to confirm your account");
            }

            CreatePasswordHash(message.Password, out byte[] passwordHash, out byte[] passwordSalt);

            if (!VerifyPasswordHash(message.Password, passwordHash, passwordSalt))
            {
                throw new Exception("Unknown error.");
            }

            if (!await _userManager.CheckPasswordAsync(user, message.Password))
            {
                if (user.AccessFailedCount == 4)
                {
                    await _userManager.SetLockoutEnabledAsync(user, true);
                    await _userManager.SetLockoutEndDateAsync(user, DateTime.UtcNow.AddHours(5));
                }

                await _userManager.AccessFailedAsync(user);

                throw new Exception("Username or password combination is not correct.");
            }

            var userRoles = await _userManager.GetRolesAsync(user);

            var authClaims = new List<Claim>
            {
                new(ClaimTypes.Name, user.UserName!),
                new(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
            };

            foreach (var userRole in userRoles)
            {
                authClaims.Add(new Claim(ClaimTypes.Role, userRole));
            }


            var signInResult = await _signInManager.PasswordSignInAsync(message.UserName, message.Password, true, lockoutOnFailure: false);

            if (signInResult.RequiresTwoFactor)
            {
                throw new Exception("Enter the code generated by your authenticator app.");
            }

            var token = GetToken(authClaims);

            user.LastLoginDate = DateTime.UtcNow;
            await _userManager.UpdateAsync(user);

            return new LoginResponseDto
            {
                UserName = message.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                IsExternal = string.IsNullOrEmpty(user.PasswordHash),
                Token = new TokenDto
                {
                    AccessToken = new JwtSecurityTokenHandler().WriteToken(token),
                    ExpiresIn = new DateTimeOffset(token.ValidTo).ToUnixTimeMilliseconds()
                }
            };
        }

        public async Task<RegisterUserResponseDto> RegisterNewUserAsync(RegisterUserRequestDto message)
        {
            if (await _userManager.FindByEmailAsync(message.Email) != null
            || await _userManager.FindByNameAsync(message.UserName) != null)
            {
                throw new Exception("User with given email or username already exists in the system");
            }

            CreatePasswordHash(message.Password, out byte[] passwordHash, out byte[] passwordSalt);
                        
            var newUser = new ApplicationUser
            {
                UserName = message.UserName,
                NormalizedUserName = message.UserName.ToUpper(),
                FirstName = message.FirstName,
                LastName = message.LastName,
                Email = message.Email,
                NormalizedEmail = message.Email.ToUpper(),
                Created = DateTime.UtcNow,
                HasFirstLogin = false,
                IsDeleted = false,
                PhoneNumber = message.PhoneNumber,
                SecurityStamp = Guid.NewGuid().ToString(),
                EmailConfirmed = false,
                PasswordHash = passwordHash.ToString()
            };

            var newUserResult = await _userManager.CreateAsync(newUser, message.Password);

            if (newUserResult.Succeeded)
            {
                throw new Exception("Make sure that all mandatory fields are filled and password satisfies the security policy.");
            }

            var emailList = new List<string>
            {
                newUser.Email
            };

            string link = $"{_configuration["ConnectionStrings:Uri"]}/login";

            var emailBody = String.Format(@"<h1 style='text-align: center'>Welcome to GKTodoManager!</h1>
                    <br><br><h3 style='text-align: center'>Manage your Tasks like a Pro.  
                    <br>Be responsible!</h3>
                    <br><br><a style='text-align: center;background-color: white;color: black;text-decorator: none;' href={0}>Login</a>", link);

            var emailSend = _emailSender.SendEmailAsync(emailList, "New user", emailBody);
            emailSend.Wait();

            return _mapper.Map<RegisterUserResponseDto>(newUser);
        }

        public async Task<string> DeleteUserAsync(string userName)
        {
            var user = await _userManager.FindByNameAsync(userName);

            if (user == null)
            {
                throw new Exception("Given user name does not exist in the system");
            }

            await _userManager.DeleteAsync(user);
            return user.Id;
        }

        public async Task<bool> UnlockUserAsync(string userName)
        {
            var user = await _userManager.FindByNameAsync(userName);

            if (user == null)
            {
                throw new Exception("Given user name does not exist in the system");
            }

            if (!await _userManager.IsLockedOutAsync(user))
            {
                throw new Exception("User account is not locked.");
            }

            await _userManager.SetLockoutEnabledAsync(user, false);
            await _userManager.SetLockoutEndDateAsync(user, DateTime.UtcNow);

            return true;
        }


        private JwtSecurityToken GetToken(List<Claim> authClaims)
        {
            var authSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT:Secret"]));

            var token = new JwtSecurityToken(
                issuer: _configuration["JWT:ValidIssuer"],
                audience: _configuration["JWT:ValidAudience"],
                expires: DateTime.Now.AddHours(3),
                claims: authClaims,
                signingCredentials: new SigningCredentials(authSigningKey, SecurityAlgorithms.HmacSha256));

            return token;
        }

        private void CreatePasswordHash(string password, out byte[] passwordHash, out byte[] passwordSalt)
        {
            using (var hmac = new HMACSHA512())
            {
                passwordSalt = hmac.Key;
                passwordHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(password));
            }
        }

        private bool VerifyPasswordHash(string password, byte[] passwordHash, byte[] passwordSalt)
        {
            using (var hmac = new HMACSHA512(passwordSalt))
            {
                var computeHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(password));
                return computeHash.SequenceEqual(passwordHash);
            }
        }
    }
}
